name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repo incluyendo LFS
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # 2) Configura GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3) Empaqueta todo el contenido de la raíz (HTML + carpeta _files + .nojekyll)
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      # 4) Despliega en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
