name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (incluyendo LFS)
        uses: actions/checkout@v3
        with:
          lfs: true          # <— esto hace que se descarguen los blobs LFS reales

      - name: (Opcional) Asegurar que Git LFS esté listo
        run: |
          git lfs install
          git lfs pull      # <— por si acaso vuelven a quedar punteros

      - name: Prepare Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./           # apunta a tu carpeta raíz con index.html y recursos

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

